[project]
name = "agen-mrk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=1.14.4",
    "crewai-tools>=1.14.4",
    "customtkinter>=5.2.2",
    "fastmcp>=3.2.4",
    "openai>=2.35.1",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "fastapi>=0.110.0",
    "uvicorn>=0.28.0",
    "sqlalchemy>=2.0.25",
    "pyjwt>=2.8.0",
    "bcrypt>=4.1.2",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2-binary>=2.9.9",
]
